Assignment 4 - Hunter Thompson & Hunter Allen
IntelliTect-Samples/EWU-CSCD371-2023-Winter pull request #100
Opened 2023-02-07 06:56 UTC by StrangeRanger

@hallen10

2023-02-09 01:02 UTC, GeorgeKoralski007 requested changes
I will review

2023-02-09 02:21 UTC, JessicaH46 commented
Define a full name record (first, last, middle) handling optional and null appropriately. ✔
Provide a comment on the full name record on why you selected to define a value or a reference type and ✔
Provide a comment on the full name record on why or why not the type is immutable. ✔
Define an IEntity interface: ✔
Add an Id property of type Guid that is an init-only setter. ✔
Add a Name property that is string. ✔
Define an abstract base class that implements IEntity - appropriately choosing to implement the interface explicitly or implicitly. ✔
Do not implement the Name property in this abstract class. ✔
Do force any derived classes to provide an implementation for Name. ✔
Define book, student, and employee records - all with entity capabilities. ✔
Choose a thoughtful approach for the value of Name for each type of entity. In all cases, there should be no backing field for Name (not even one generated by an automatically implemented property) - consider a calculated property. ✔
Provide a comment on each interface member in each entity explaining why you implemented it implicitly or explicitly. ✔
You should consider the relationship between Student and Employee and refactor the common code shared between them. ✔
Given the properties on the full name record, you should consider which entities it makes sense to use it. ✔
Test that the equality behavior on these entities behaves as expected. ✔
Provide a comment on each interface method explaining why you implemented it implicitly or explicitly.
Unit test the Storage class using various entities to ensure that there are no bugs.

I think your code looks really good, your tests are very thorough and well written. Also we were having problems on our code with the inheritance but I saw that you used sealed, which I think works great and was helpful even though I was reviewing your code! Great job!

2023-02-09 04:50 UTC, GeorgeKoralski007 commented
**Tasks**
Define a full name record (first, last, middle) handling optional and null appropriately. ✔
Provide a comment on the full name record on why you selected to define a value or a reference type and ✔
Provide a comment on the full name record on why or why not the type is immutable. ✔
Define an IEntity interface: ✔
Add an Id property of type Guid that is an init-only setter. ✔
Add a Name property that is string. ✔
Define an abstract base class that implements IEntity - appropriately choosing to implement the interface explicitly or implicitly. ✔
Do not implement the Name property in this abstract class. ✔
Do force any derived classes to provide an implementation for Name. ✔
Define book, student, and employee records - all with entity capabilities. ✔
Choose a thoughtful approach for the value of Name for each type of entity. In all cases, there should be no backing field for Name (not even one generated by an automatically implemented property) - consider a calculated property. ✔
Provide a comment on each interface member in each entity explaining why you implemented it implicitly or explicitly. ✔
You should consider the relationship between Student and Employee and refactor the common code shared between them. ✔
Given the properties on the full name record, you should consider which entities it makes sense to use it. ✔
Test that the equality behavior on these entities behaves as expected. ✔
Provide a comment on each interface method explaining why you implemented it implicitly or explicitly.
Unit test the Storage class using various entities to ensure that there are no bugs.
Code review (using TODO: comments if there are any issues - which there may not be) all logger-related classes.)
Pay special attention to the CreateLogger methods throughout.
**Fundamentals**
Be sure you enable:
Enable Nullability for all projects ✔
Set LangVersion and the TargetFramework to the latest released versions available (preview versions optional) ✔
Ensure that you turn on code analysis for all projects(EnableNETAnalyzers) ✔
Ensure there are no errors or warnings (including code analysis warnings) ✔
All of the above should be unit tested ✔
Choose simplicity over complexity ✔
**Extra Credit**
Refactor your project files to put common properties and/or items into a single file. ❌
Convert ILogger.CreateLogger to a generic method. ❌ 
Returns the logger classes type that is to be created. ❌✔
Has a type parameter for the configuration type ❌
================================================================
Your project Builds
2 of your Tests do not pass (AreSame_Book and Create_Student_WithMiddleName)

2023-02-09 04:51 UTC, GeorgeKoralski007 commented on Logger/Entity.cs
> +    protected Entity(Guid id, string? name = null)
param name is not used

2023-02-09 05:26 UTC, GeorgeKoralski007 commented on Logger.Tests/BookTest.cs
> +        Assert.IsTrue(book1.Equals(book2));
test is failing because id for each record is different. You can compare Assert.AreEqual(book1.ToString(),book2.ToString());

2023-02-09 05:34 UTC, GeorgeKoralski007 commented on Logger.Tests/StudentTest.cs
> +        Assert.AreEqual("Doe", student.LastName);
Your test is failing because your implementation of the Name setter incorrectly assigned middle and last name.

2023-02-09 05:37 UTC, GeorgeKoralski007 commented on Logger/Student.cs
> +            string lastName = array[1];
We should assume Name is not always (valid with 2 or 3 names). Otherwise accessing array may be out of range.
Validate array.Count before that

2023-02-09 05:42 UTC, GeorgeKoralski007 commented on Logger/Student.cs
> +            string middleName = array.Length > 2 ? array[2] : null; // TODO: MAKE THIS BETTER
Correct input value should be:
"First Last" or "First Middle Last"
In your case you assign middleName to Last, hence your unit test fails.
My suggestion is:
if (array.Length == 3)
{
  middleName = array[1];
  lastName = array[2];
}

2023-02-09 05:45 UTC, GeorgeKoralski007 commented on Logger/Entity.cs
> +    public Guid Id { get; init; }
You can initialize the Id to be Guid.NewGuid() instead of having each subclass do the same work.

2023-02-09 05:49 UTC, GeorgeKoralski007 commented on Logger/Employee.cs
> +public record class Employee : Entity
Employee and Student are the same and you have code duplication.
You can have specific property that applies only for one of the classes.
All common properties can be in a base Person class for example.

2023-02-09 05:50 UTC, GeorgeKoralski007 requested changes
Please review my comments

2023-02-09 06:56 UTC, StrangeRanger commented on Logger/Entity.cs
> +    protected Entity(Guid id, string? name = null)
Looking back at it, I could have changed it were the name parameter was never specified, then convert the constructor into a primary constructor. 
Thanks for pointing that out for me.

2023-02-09 21:03 UTC, StrangeRanger commented on Logger.Tests/BookTest.cs
> +        Assert.IsTrue(book1.Equals(book2));
No longer applicable

2023-02-09 21:03 UTC, StrangeRanger commented on Logger.Tests/StudentTest.cs
> +        Assert.AreEqual("Doe", student.LastName);
No longer applicable

2023-02-09 21:04 UTC, StrangeRanger commented on Logger/Student.cs
> +            string middleName = array.Length > 2 ? array[2] : null; // TODO: MAKE THIS BETTER
No longer applicable

2023-02-09 21:05 UTC, StrangeRanger commented on Logger/Entity.cs
> +    public Guid Id { get; init; }
No longer applicable

2023-02-09 21:34 UTC, StrangeRanger commented on Logger/Employee.cs
> +public record class Employee : Entity
Thank you for your input here, and answering the question I left.

2023-02-16 23:40 UTC, mmwoodfo commented on Logger.Tests/BookTest.cs
> +    public void AreSame_Book()
Maybe also check for inequality!

2023-02-16 23:40 UTC, mmwoodfo commented on Logger/Entity.cs
> +public abstract record class Entity(Guid Id) : IEntity
```suggestion
public abstract record class BaseEntity(Guid Id) : IEntity
```

2023-02-16 23:40 UTC, mmwoodfo commented on Logger/IEntity.cs
> +    public string Name { get; }
```suggestion
    Guid Id { get; init; }
    string Name { get; }
```

2023-02-16 23:40 UTC, mmwoodfo commented on Logger/Person.cs
> +    public string FirstName
Do you think it would make more sense to just make the FullName property public rather than having these extra methods?

2023-02-16 23:40 UTC, closed without merging

2023-02-17 07:51 UTC, StrangeRanger commented on Logger/Person.cs
> +    public string FirstName
Now that I think about it, probably

2023-02-17 07:52 UTC, StrangeRanger commented on Logger/IEntity.cs
> +    public string Name { get; }
I get the ID, but why would we want the make Name private?

2023-02-17 07:52 UTC, StrangeRanger commented on Logger/Entity.cs
> +public abstract record class Entity(Guid Id) : IEntity
If it's a base element, is it ideal to always prefix it as such?