Assignment5 with alowe4
IntelliTect-Samples/EWU-CSCD371-2023-Winter pull request #112
Opened 2023-02-13 23:02 UTC by jdriscoll1

Extra Credit Attempted

2023-02-16 04:44 UTC, GeorgeKoralski007 commented
I will review

2023-02-16 04:50 UTC, GeorgeKoralski007 commented on GenericsHomework/GenericsHomework.Tests/Node.Tests.cs
> +            Assert.IsNotNull(TestNode);
This is not testing your main code. Its testing your test (that TestNode is initialized).
You dont need to test that test framework will call TestInitialize method.
You can remove this test

2023-02-16 04:53 UTC, GeorgeKoralski007 commented on GenericsHomework/GenericsHomework.Tests/Node.Tests.cs
> +            Assert.IsTrue(TestNode.Exists("Test Node"));
You should also test the false case when value is missing.

2023-02-16 04:55 UTC, GeorgeKoralski007 commented on GenericsHomework/GenericsHomework.Tests/Node.Tests.cs
> +            Assert.IsTrue(TestNode.Exists("Test Node"));
You only test the value.
Also you should assert that both nodes are connected with .Next

2023-02-16 05:00 UTC, GeorgeKoralski007 commented on GenericsHomework/GenericsHomework/Node.cs
> +        public override string ToString()
Project requirement is:
Add a ToString() override that writes out the value's ToString() result. 
This means you only need to return Value.ToString() and should not walk the whole list

2023-02-16 05:06 UTC, GeorgeKoralski007 commented on GenericsHomework/GenericsHomework/Node.cs
> +        IEnumerator<TNodeType> IEnumerable<TNodeType>.GetEnumerator()
This method and the one above has duplicate code.
Can you call from one method the other one to avoid duplication?

2023-02-16 05:10 UTC, GeorgeKoralski007 commented on GenericsHomework/GenericsHomework.Tests/Node.Tests.cs
> +            TestNode.Clear();
Please test that TestNode.Next is the same as TestNode

2023-02-16 05:10 UTC, GeorgeKoralski007 commented on GenericsHomework/GenericsHomework.Tests/Node.Tests.cs
> +
Remove all empty lines where not needed

2023-02-16 05:12 UTC, GeorgeKoralski007 commented on GenericsHomework/GenericsHomework.Tests/Node.Tests.cs
> +            Assert.IsTrue(TestNode.Exists("2"));
Also test when Exists will return false.

2023-02-16 05:12 UTC, GeorgeKoralski007 commented on GenericsHomework/GenericsHomework.Tests/Node.Tests.cs
> +            Assert.IsTrue(TestNode.Contains("2"));
Test when it will be false

2023-02-16 05:16 UTC, GeorgeKoralski007 commented on GenericsHomework/GenericsHomework.Tests/Node.Tests.cs
> +            Assert.AreEqual<string>(string.Join(" ", arr), TestNode.ToString().Trim());
You can use CollectionAssert.AreEqual instead of relying on ToString

2023-02-16 05:19 UTC, GeorgeKoralski007 commented on GenericsHomework/GenericsHomework.Tests/Node.Tests.cs
> +            TestNode.Clear();
You dont need to call Clear at the end of each test.
It will be initialized for each test anyway

2023-02-16 05:21 UTC, GeorgeKoralski007 requested changes
Please review

2023-02-16 05:26 UTC, GeorgeKoralski007 commented
Create a class library project called "GenericsHomework.". ✔
Create a node class that can contain a value of any type and points to the next node and traversing the next node points back to the first item.
Define the Node class
The values should be homogeneous.
Include a constructor that takes a value. (No validation is necessary on the value). ✔
Add a ToString() override that writes out the value's ToString() result. ❌your code returns the whole list (should be a single value)
Add a Next property that references the next node or else refers back to itself if there are no other nodes in the list. ✔
The Next property should be non-nullable (careful to follow the non-nullable property guidelines) ❌Doesn't need to be nullable
The Next property setter should be private. ✔
Add an Append method that takes a value and appends a new Node instance after the current node (by invoking the Next property). ✔
Add a Clear method that effectively removes all items from a list except the current node. Pay attention as to whether you should be concerned with the following:
Whether it is sufficient to only set Next to itself ✔
Whether to set the removed items to circle back on themselves. In other words, whether to close the loop of the removed items. (Provide a test to show why this is required if it is required). ✔
Given there is a circular list of items, provide a comment to indicate whether you need to worry about garbage collection because all the items point to each other and therefore may never be garbage collected. ✔
Create an Exists method to test to see if a value exists in the list. ✔
Throw an error on an attempt to Append a duplicate value. (Make sure you test for this case) ✔
You should not rely on any BCL generic classes for your implementation. ✔
Fundamentals
Place all shared project properties into a Directory.Build.Props file.
Place all shared project items into a Directory.Build.targets file.
nullable reference types is enabled ✔
Ensure that you turn on code analysis for all projects(EnableNETAnalyzers) ✔
Set LangVersion and the TargetFramework to the latest released versions available (preview versions optional) ✔
and enabled .NET analyzers for both projects ✔
For this assignment, always use Assert.AreEqual<T>() (the generic version) ✔
All of the above should be unit tested ✔
Choose simplicity over complexity ✔

2023-02-16 18:45 UTC, jdriscoll1 commented on GenericsHomework/GenericsHomework/Node.cs
> +        IEnumerator<TNodeType> IEnumerable<TNodeType>.GetEnumerator()
Thank you for the feedback. I looked for methods to rewrite the code without duplication; and, of what was attempted the current solution is the cleanest.

2023-02-21 23:33 UTC, mmwoodfo reviewed
Great job!

2023-02-21 23:33 UTC, mmwoodfo commented on GenericsHomework/GenericsHomework/Node.cs
> +        private Node<TNodeType>? _Next { get; set; }
```suggestion
        private Node<TNodeType>? _Next;
```

2023-02-21 23:33 UTC, mmwoodfo commented on GenericsHomework/GenericsHomework/Node.cs
> +            Console.WriteLine(newNode.Value);
```suggestion
```

2023-02-21 23:33 UTC, mmwoodfo commented on GenericsHomework/GenericsHomework/Node.cs
> +        private Node(TNodeType value, Node<TNodeType> next) {
```suggestion
        private Node(TNodeType value) {
```
Just set next to `this` when creating a new node.

2023-02-21 23:33 UTC, mmwoodfo commented on GenericsHomework/GenericsHomework/Node.cs
> +        }
```suggestion
        public override string? ToString()
        {
            return Value?.ToString();
        }
```

2023-02-21 23:33 UTC, closed without merging