Assignment5 1bbartels
IntelliTect-Samples/EWU-CSCD371-2023-Winter pull request #123
Opened 2023-02-14 04:38 UTC by 1bbartels

2023-02-16 03:14 UTC, lsobtafo commented on GenericsHomework/Node.cs
> +
Try to use properties instead of public fields for Value and Next. Try using properties with a private set method to control how the fields are accessed and modified.

2023-02-16 05:39 UTC, Afterlyte requested changes
## Instructions

- Create a *class library* project called "GenericsHomework.". ✔
- Create a node class that can contain a value of any type and points to the next node and traversing the next node points back to the first item.
  - Define the `Node` class
  - The values should be homogeneous.
  - Include a constructor that takes a value.  (No validation is necessary on the value). ✔
  - Add a `ToString()` override that writes out the value's `ToString()` result. ✔
  - Add a `Next` property that references the next node or else refers back to itself if there are no other nodes in the list. ❌
    - **This should be modified so that the property is doing the referencing back to itself instead of managing that in other places of the code**
    - The `Next` property should be non-nullable (careful to follow the non-nullable property guidelines) ❌
     - **Similar note as above**
    - The `Next` property setter should be private. ✔
  - Add an `Append` method that takes a value and appends a new `Node` instance after the current node (by invoking the `Next` property). ✔
  - Add a Clear method that effectively removes all items from a list except the current node. Pay attention as to whether you should be concerned with the following:
    - Whether it is sufficient to only set Next to itself ✔
    - Whether to set the removed items to circle back on themselves. In other words, whether to close the loop of the removed items. (Provide a test to show why this is required if it is required). ❌
     - **Only functionality right now is setting Next to itself**
    - Given there is a circular list of items, provide a comment to indicate whether you need to worry about garbage collection because all the items point to each other and therefore may never be garbage collected. ❌
      - **Same as above note, no other functionality is there**
  - Create an Exists method to test to see if a value exists in the list. ✔
  - Throw an error on an attempt to Append a duplicate value. (Make sure you test for this case) ✔
- You should not rely on any BCL generic classes for your implementation. ✔

## Extra Credit

Do one of the following two options (or both if you want extra, extra credit) :)

1. Implement a `VennDiagram` structure that contains `n` `Circle`s that only contains homogenous **reference types** of any type. ❌

- Each circle contains n items and each item can belong to one or more `Circle` instances.
- You are not required to use a `Node` from earlier in the homework for your Venn diagram implementation.
- You are welcome to use existing BCL generic classes for the extra credit.

1. Implement `System.Collections.Generic.ICollection<T>` on the `Node` class ❌

## Fundamentals

- Place all shared project properties into a `Directory.Build.Props` file. ❌
- Place all shared project items into a `Directory.Build.targets` file. 
- nullable reference types is enabled  ✔
- Ensure that you turn on code analysis for all projects(EnableNETAnalyzers)  ✔
- Set LangVersion and the TargetFramework to the latest released versions available (preview versions optional)   ✔
- and enabled .NET analyzers for both projects ✔
- For this assignment, always use `Assert.AreEqual<T>()` (the generic version)  ❌
  - **AreEqual was never used in the first place (you probably should since it's useful for more precise data validation rather than just using IsTrue on the Exists method**
- All of the above should be unit tested ✔
- Choose simplicity over complexity ✔

Overall well done on the main fundamentals, main things to work on are more precise unit tests and some bits and pieces of code in the primary functionalities of the project (like the properties, ToString, Append, etc.

2023-02-23 01:27 UTC, mmwoodfo reviewed
There were alot of good comments left by your peers on this PR.

2023-02-23 01:27 UTC, mmwoodfo commented on GenericsHomework.Tests/Node.Tests.cs
> +    [TestClass]
It would be good to have some more tests that test various lengths of your list against your different methods.

2023-02-23 01:27 UTC, closed without merging