Assignment6 - Joshua Willis
IntelliTect-Samples/EWU-CSCD371-2023-Winter pull request #132
Opened 2023-02-18 23:00 UTC by WobblyRunner

I took a little time to go above-and-beyond with my implementation here. This solution allows for complex expressions to be evaluated while still abiding by the TryParse pattern. I updated the README.md as a reference to see what I included and did include. I did the refactoring extra credit but still included my base implementation and tests for Calculator.cs as well.

2023-02-23 03:12 UTC, Afterlyte commented
I will review this

2023-02-23 04:40 UTC, Afterlyte requested changes
## Instructions

- Create a *Console* project called "Calculate.". ✔
- Define a Program Class
  - Define two init-only setter properties, `WriteLine` and `ReadLine`, that contain delegates for writing a line of text and reading a line of text respectively ✔
  - Write a test that sets these properties at construction time and then invokes the properties and verifies the expected behavior occurs. ✔
  - Set the default behavior for the `WriteLine` and `ReadLine` properties to invoke `System.Console` versions of the methods and add an empty default constructor. ✔
- Define a Calculator class ✔
  - Define static `Add`, `Subtract`, `Multiple`, and `Divide` methods that have two parameters and return a third parameter. ✔
  - Define a read-only property, `MathematicalOperations`, of type `System.Collections.Generics.IReadOnlyDictionary<TKey,TValue>` that:
    - is initialized to a `System.Collections.Generics.Dictionary<<TKey,TValue>` instance that. ✔
      - Uses `char` for the key corresponding to the operators +, -, *, and /. ✔
      - Has values that correspond with the Add, Subtract, Multiple, and Divide methods. ✔
  - Implement a `TryCalculate` method following "TryParse" pattern ✔
    - Valid `calculation` expressions include such strings as "3 + 4", "42 - 2", etc. ✔
     - **You went a little above that but hey the standard requirement still works**
    - If there is no whitespace around the operator, you can assume the `calculation` is invalid and return false. Similarly if the operands are not integers. ✔
      - **Technically you didn't do this but because you handled whitespace properly**
    - Use `string.Split()`, pattern matching, logical and operators to parse the string in their entirety ❌
      - **It doesn't look like you used pattern matching at all on the expressions, but instead did indexing on the string** 
    - Index into the `MathematicalOperations` method using the operator parsed during pattern matching to find the corresponding implementation and invoke it. ✔
- Implement the Program class to instantiate the calculator and invoke it based on user input from the console. ✔
- Be sure to use the `WriteLine`/`ReadLine` properties on `Program` for testing the input and output of your program. ❌
  - **program.ReadLine/WriteLine was used in the actual main method, but never used during testing.**

## Extra Credit

Do one of the following two options (or both if you want extra, extra credit) :)

- Refactor the redirect portion of the `Program` class into 'ProgramBase` ❌
- Move ProgramBase into a ConsoleUtilities assembly to be used in other console-based projects ❌
- Use generics the mathematical operations methods and consider using generic constraints (requires .NET 7.0) ✔

## Fundamentals

- Place all shared project properties into a `Directory.Build.Props` file. ✔
  - **There's a duplicate file but the correct one still works**
- Place all shared project items into a `Directory.Build.targets` file. 
- nullable reference types is enabled  ✔
- Ensure that you turn on code analysis for all projects(EnableNETAnalyzers)  ❌
  - **NET analyzers are not enabled on the correct version of the file**
- Set LangVersion and the TargetFramework to the latest released versions available (preview versions optional)   ✔
- and enabled .NET analyzers for both projects ❌
- For this assignment, always use `Assert.AreEqual<T>()` (the generic version)  ✔
- All of the above should be unit tested ❌
  - **Missing unit tests on using Program.ReadLine/WriteLine when doing the calculations but good other than that.**
- Choose simplicity over complexity ✔
  - **Well, debatable but you made complex functionality so it counts**

**Overall really good and clever extra functionality, mainly missing some unit tests and missing the pattern matching on the expression input**

2023-02-23 04:40 UTC, Afterlyte commented on Calculate/Calculate.Tests/GenericCalculatorTests.cs
> +	}
I really appreciate the formatting of your tests, very readable and consistent

2023-02-23 04:40 UTC, Afterlyte commented on Calculate/Calculate/Calculator.cs
> +		int index = expression.LastIndexOfAny(Operators);
I like this way of dynamically determining the last used operator. This looks a lot more reliable for more dynamic solutions like this

2023-02-23 04:40 UTC, Afterlyte commented on Calculate/Calculate/Calculator.cs
> +				&& TryCalculate(expression[..index], out int left))
Pattern matching is never used which is one of the requirements

2023-02-23 04:40 UTC, Afterlyte commented on Calculate/Calculate.Tests/CalculatorTests.cs
> +		bool success = TestCalculator.TryCalculate(expression, out int actual);
Program.ReadLine/WriteLine needs to be used in testing to test that the assigned methods are giving the expected behavior

2023-02-23 04:40 UTC, Afterlyte commented on Calculate/Directory.Build.props
> +  <PropertyGroup>
EnableNETAnalyzers missing from the working props file

2023-02-23 07:33 UTC, JessicaH46 commented
Create a Console project called "Calculate.". ✔
Define a Program Class
Define two init-only setter properties, WriteLine and ReadLine, that contain delegates for writing a line of text and reading a line of text respectively ✔
Write a test that sets these properties at construction time and then invokes the properties and verifies the expected behavior occurs. ✔
Set the default behavior for the WriteLine and ReadLine properties to invoke System.Console versions of the methods and add an empty default constructor. ✔
Define a Calculator class ✔
Define static Add, Subtract, Multiple, and Divide methods that have two parameters and return a third parameter. ✔
Define a read-only property, MathematicalOperations, of type System.Collections.Generics.IReadOnlyDictionary<TKey,TValue> that:
is initialized to a System.Collections.Generics.Dictionary<<TKey,TValue> instance that. ✔
Uses char for the key corresponding to the operators +, -, *, and /. ✔
Has values that correspond with the Add, Subtract, Multiple, and Divide methods. ✔
Implement a TryCalculate method following "TryParse" pattern ✔
Valid calculation expressions include such strings as "3 + 4", "42 - 2", etc. ✔
You went a little above that but hey the standard requirement still works
If there is no whitespace around the operator, you can assume the calculation is invalid and return false. Similarly if the operands are not integers. ✔
Technically you didn't do this but because you handled whitespace properly
Use string.Split(), pattern matching, logical and operators to parse the string in their entirety ❌
It doesn't look like you used pattern matching at all on the expressions, but instead did indexing on the string
Index into the MathematicalOperations method using the operator parsed during pattern matching to find the corresponding implementation and invoke it. ✔
Implement the Program class to instantiate the calculator and invoke it based on user input from the console. ✔
Be sure to use the WriteLine/ReadLine properties on Program for testing the input and output of your program. ❌✔?
program.ReadLine/WriteLine was used in the actual main method, but never used during testing.

I think you did really good on your code, most of the main components re done from what I saw. I think some of your fundamentals are missing but those are quick fixes! You also have a duplicte file for your Directory build props. Also for one of the requirements, readline writeline, I think you might need to add your Console.ReadLine here
`public Action<string> WriteLine { get; init; } = Console.WriteLine;
  public Func<string> ReadLine { get; init; } = Console.ReadLine;`
I had it like yours at first and it didn't work properly for mine at least. Everything else looks good, great work!

2023-02-24 05:56 UTC, vicdotexe commented on Calculate/Calculate/Calculator.cs
> +	public bool TryCalculate(string expression, out int result)
TryCalculate("FiveMinusFive", out int result);
Assert.AreEqual(0,result);
//what kind of magic is this?

2023-02-28 22:13 UTC, mmwoodfo reviewed
Awesome job, this looks great!

2023-02-28 22:13 UTC, closed without merging