Assignment6 lambda expressions @avanchu253
IntelliTect-Samples/EWU-CSCD371-2023-Winter pull request #140
Opened 2023-02-21 00:45 UTC by randypipkins

2023-02-22 19:05 UTC, hallen10 commented
I will review this.

2023-02-22 19:29 UTC, hallen10 requested changes
## Instructions

- Create a *Console* project called "Calculate.". ✔
- Define a Program Class
  - Define two init-only setter properties, `WriteLine` and `ReadLine`, that contain delegates for writing a line of text and reading a line of text respectively ✔
  - Write a test that sets these properties at construction time and then invokes the properties and verifies the expected behavior occurs. ✔
  - Set the default behavior for the `WriteLine` and `ReadLine` properties to invoke `System.Console` versions of the methods and add an empty default constructor. ✔
- Define a Calculator class ✔
  - Define static `Add`, `Subtract`, `Multiple`, and `Divide` methods that have two parameters and return a third parameter. ✔
  - Define a read-only property, `MathematicalOperations`, of type `System.Collections.Generics.IReadOnlyDictionary<TKey,TValue>` that:
    - is initialized to a `System.Collections.Generics.Dictionary<<TKey,TValue>` instance that. ✔
      - Uses `char` for the key corresponding to the operators +, -, *, and /. ✔
      - Has values that correspond with the Add, Subtract, Multiple, and Divide methods. ✔
  - Implement a `TryCalculate` method following "TryParse" pattern ✔
    - Valid `calculation` expressions include such strings as "3 + 4", "42 - 2", etc. ✔
    - If there is no whitespace around the operator, you can assume the `calculation` is invalid and return false. Similarly if the operands are not integers. ✔
    - Use `string.Split()`, pattern matching, logical and operators to parse the string in their entirety ✔
    - Index into the `MathematicalOperations` method using the operator parsed during pattern matching to find the corresponding implementation and invoke it. ✔
- Implement the Program class to instantiate the calculator and invoke it based on user input from the console. ✔
- Be sure to use the `WriteLine`/`ReadLine` properties on `Program` for testing the input and output of your program. ✔

## Fundamentals

- Place all shared project properties into a `Directory.Build.Props` file.
- Place all shared project items into a `Directory.Build.targets` file.
- nullable reference types is enabled  ✔
- Ensure that you turn on code analysis for all projects(EnableNETAnalyzers)  ✔
- Set LangVersion and the TargetFramework to the latest released versions available (preview versions optional)   ✔
- and enabled .NET analyzers for both projects ✔
- For this assignment, always use `Assert.AreEqual<T>()` (the generic version)  ✔
- All of the above should be unit tested ✔
- Choose simplicity over complexity ✔

2023-02-22 19:29 UTC, hallen10 commented on Calculate/Calculate/Program.cs
> +        Calculator calculator = new();
Never gets used.

2023-02-23 03:28 UTC, arose-13 commented
Gonna review this

2023-02-23 03:51 UTC, arose-13 reviewed
* Create a Console project called "Calculate.". ✔
* Define a Program Class
** Define two init-only setter properties, WriteLine and ReadLine, that contain delegates for writing a line of text and reading a line of text respectively ✔
** Write a test that sets these properties at construction time and then invokes the properties and verifies the expected behavior occurs. ✔
** Set the default behavior for the WriteLine and ReadLine properties to invoke System.Console versions of the methods and add an empty default constructor. ❌
* Define a Calculator class ✔
** Define static Add, Subtract, Multiple, and Divide methods that have two parameters and return a third parameter. ✔
** Define a read-only property, MathematicalOperations, of type System.Collections.Generics.IReadOnlyDictionary<TKey,TValue> that:
*** is initialized to a System.Collections.Generics.Dictionary<<TKey,TValue> instance that. ✔
*** Uses char for the key corresponding to the operators +, -, *, and /. ✔
*** Has values that correspond with the Add, Subtract, Multiple, and Divide methods. ✔
** Implement a TryCalculate method following "TryParse" pattern ✔
** Valid calculation expressions include such strings as "3 + 4", "42 - 2", etc. ✔
** If there is no whitespace around the operator, you can assume the calculation is invalid and return false. Similarly if the operands are not integers. ✔
** Use string.Split(), pattern matching, logical and operators to parse the string in their entirety ✔
** Index into the MathematicalOperations method using the operator parsed during pattern matching to find the corresponding implementation and invoke it. ✔
* Implement the Program class to instantiate the calculator and invoke it based on user input from the console. ❌
* Be sure to use the WriteLine/ReadLine properties on Program for testing the input and output of your program. ✔
## Fundamentals
* Place all shared project properties into a Directory.Build.Props file. ✔
* Place all shared project items into a Directory.Build.targets file.
* nullable reference types is enabled ✔
* Ensure that you turn on code analysis for all projects(EnableNETAnalyzers) ✔
* Set LangVersion and the TargetFramework to the latest released versions available (preview versions optional) ✔
* and enabled .NET analyzers for both projects ✔
* For this assignment, always use Assert.AreEqual<T>() (the generic version) ❌
* All of the above should be unit tested ✔
* Choose simplicity over complexity ✔

Very good job! All you really need to do is add the default constructor for `Program` and change a couple things that I mention in some other comments. Well done!

2023-02-23 03:51 UTC, arose-13 commented on Calculate/Calculate.Tests/ProgramTests.cs
> +        Assert.AreEqual("test", expected.ToString().Trim());
You need to use the generic version of this.

2023-02-23 03:51 UTC, arose-13 commented on Calculate/Calculate/Program.cs
> +            else if(input != null && Calculator.TryCalculate(input, out double output))
```suggestion
            else if(input != null && calculator.TryCalculate(input, out double output))
```
By using `Calculator` here, your instance `calculator` technically goes unused.

2023-02-23 03:51 UTC, arose-13 commented on Calculate/Calculate/Program.cs
> +public class Program
While a default constructor is added by the compiler, the instructions do say to "add an empty default constructor".

2023-03-01 00:13 UTC, mmwoodfo commented on Calculate/Calculate.Tests/CalculatorTests.cs
> +public class CalculatorTests
Maybe a test for dividing by 0 and some tests for non numeric input

2023-03-01 00:13 UTC, mmwoodfo commented on Calculate/Calculate/Program.cs
> +public class Program
Yes, as well as a constructor for setting write/read line behavior

2023-03-01 00:13 UTC, mmwoodfo commented on Calculate/Calculate/Calculator.cs
> +    }
```suggestion
    public static double Add(int a, int b) => a + b;
```
for simple methods, you can make them a single line

2023-03-01 00:13 UTC, mmwoodfo commented on Calculate/Calculate/Calculator.cs
> +        },
This would be a case where it would be okay to write this all on one line.
`{ '+', Add }`
This isn't a big deal, and can be chaulked up to personal preference.

2023-03-01 00:13 UTC, mmwoodfo commented on Calculate/Calculate/Calculator.cs
> +        string[] inputArray = input.Split(" ");
You should be using the Split method along side pattern matching. e.g.
`if (expression?.Split(" ") is [string operator1, [char mathmaticalOperator], string operand2])`

2023-03-01 00:13 UTC, mmwoodfo commented on Calculate/Calculate/Calculator.cs
> +    public bool TryCalculate(string input, out double output)
Consider making output nullable and returning null when canCalculate is false.

2023-03-01 00:15 UTC, closed without merging