Assignment7+8 @alowe4
IntelliTect-Samples/EWU-CSCD371-2023-Winter pull request #158
Opened 2023-03-01 21:34 UTC by jdriscoll1

Extra Credit Attempted
Please run: `dotnet add package System.Linq.Async --version 6.0.1` to test for it to build
Please move `People.csv` to debug folder in tests for it to be readable

2023-03-09 03:30 UTC, AnnikaStachowiak reviewed
Implement the ISampleData.CsvRows property, loading the data from the People.csv file and returning each line as a single string. ✔
        Change the "Copy to" property on People.csv to "Copy if newer" so that the file is deployed along with your test project. ❌✔ Not Sure
        Using LINQ, skip the first row in the People.csv. ✔
        Be sure to appropriately handle resource (IDisposable) items correctly if applicable (and it may not be depending on how you implement it). ✔

    Implement IEnumerable<string> GetUniqueSortedListOfStatesGivenCsvRows() to return a sorted, unique list of states. ✔
        Use ISampleData.CsvRows for your data source. ✔
        Don't forget the list should be unique. ✔
        Sort the list alphabetically. ✔
        Include a test that leverages a hardcoded list of addresses. ✔
        Include a test that uses LINQ to verify the data is sorted correctly (do not use a hardcoded list). ✔

    Implement ISampleData.GetAggregateSortedListOfStatesUsingCsvRows() to return a string that contains a unique, comma separated list of states. ✔
        Use ISampleData.GetUniqueSortedListOfStatesGivenCsvRows() for your data source. ✔
        Consider "selecting" only the states and calling ToArray() to retrieve an array of all the state names. ✔
        Given the array, consider using string.Join to combine the list into a single string. ✔

    Implement the ISampleData.People property to return all the items in People.csv as Person objects ✔
        Use ISampleData.CsvRows as the source of the data. ✔
        Sort the list by State, City, and Zip. (Sort the addresses first then select). ✔
        Be sure that Person.Address is also populated. ✔
        Adding null validation to all the Person and Address properties is optional.
        Consider using ISampleData.CsvRows in your test to verify your results. ✔

    Implement ISampleDate.FilterByEmailAddress(Predicate<string> filter) to return a list of names where the email address matches the filter. ✔
        Use ISampleData.People for your data source. ✔

    Implement ISampleData.GetAggregateListOfStatesGivenPeopleCollection(IEnumerable<IPerson> people) to return a string that contains a unique, comma-separated list of states. ✔
        Use the people parameter from ISampleData.People property for your data source. ✔
        At a minimum, use the System.Linq.Enumerable.Aggregate` LINQ method to create your result. ❌
        Don't forget the list should be unique. ✔
        It is recommended that, at a minimum, you use ISampleData.GetUniqueSortedListOfStatesGivenCsvRows to validate your result.

    Given the implementation of Node in Assignment5

    Implement IEnumerable<T> to return all the items in the "circle" of items. ✔
    Add an IEnumberable<T> ChildItems(int maximum) method to Node that returns the remaining items with a maximum number of items returned less than maximum.✔

Extra Credit

    Implement the homework using async/await and multi-threading by defining a new SampleDataAsync class that implements IAsyncSampleData). Refactor your SampleData and SampleDataAsync classes with minimal duplication. Be sure to refactor your tests to re-use a significant amount of the test code for both implementations. ❌ You tried but it does not appear to work.

Fundamentals

    Place all shared project properties into a Directory.Build.Props file.
    Place all shared project items into a Directory.Build.targets file.
    Ensure nullable reference types is enabled ✔
    Ensure that you turn on code analysis for all projects(EnableNETAnalyzers) ✔
    Set LangVersion and the TargetFramework to the latest released versions available (preview versions optional) ✔
    and enabled .NET analyzers for both projects ✔
    For this assignment, consider using Assert.AreEqual<T>() (the generic version) ✔
    All of the above should be unit tested ✔
    Choose simplicity over complexity ✔


TestReadCSV does not pass, along with all of your async tests. Also, there are quite a few things throughout that VS points out, such as a couple naming rule violations. Good work though.

2023-03-09 06:19 UTC, Afterlyte commented
I will review this

2023-03-09 06:31 UTC, jdriscoll1 commented
> 

Hi Ian, We added a new commit that fixes some failing tests, to get a more updated version, please pull again. Thank you.

2023-03-09 07:14 UTC, Afterlyte requested changes
## Instructions

**Throughout, consider using the `System.Linq.Enumerable` methods `Zip`, `Count`, `Sort` and `Contains` methods for testing collections.**. (Preferably avoid using `Microsoft.VisualStudio.TestTools.UnitTesting.CollectionAssert` although that might be easier, to get a firmer grasp on additional LINQ API.)

1. Implement the `ISampleData.CsvRows` property, loading the data from the `People.csv` file and returning each line as a single string. ✔
  - **This should return an IEnumerable instead of a List, i.e. the instructions for retrieving the data, not forcing the data to be fetched into a List by default**
   - Change the "Copy to" property on People.csv to "Copy if newer" so that the file is deployed along with your test project. ✔
   - Using LINQ, skip the first row in the `People.csv`. ✔
   - Be sure to appropriately handle resource (`IDisposable`) items correctly if applicable (and it may not be depending on how you implement it). ✔

2. Implement `IEnumerable<string> GetUniqueSortedListOfStatesGivenCsvRows()` to return a **sorted**, **unique** list of states. ✔
  - **Similar to number 1, you should use LINQ to be fetching the data instead of List objects and foreach loops.**
   - Use `ISampleData.CsvRows` for your data source. ✔
   - Don't forget the list should be unique. ✔
   - Sort the list alphabetically. ✔
   - Include a test that leverages a hardcoded list of addresses. ✔
   - Include a test that uses LINQ to verify the data is sorted correctly (do not use a hardcoded list). ✔

3. Implement `ISampleData.GetAggregateSortedListOfStatesUsingCsvRows()` to return a `string` that contains a **unique**, comma separated list of states. ✔

   - Use `ISampleData.GetUniqueSortedListOfStatesGivenCsvRows()` for your data source. ✔
   - Consider "selecting" only the states and calling `ToArray()` to retrieve an array of all the state names. ✔
   - Given the array, consider using `string.Join` to combine the list into a single string. ✔

4. Implement the `ISampleData.People` property to return all the items in `People.csv` as `Person` objects ✔
  - **Good understanding of what should be done, and good use of pattern matching, but again LINQ should be used to properly return IEnumerable query instructions instead of building an instantiated List.** 
   - Use `ISampleData.CsvRows` as the source of the data. ✔
   - Sort the list by State, City, and Zip. (Sort the addresses first then select). ❌
     - **Sorting should be done first before the processing of the actual data happens.**
   - Be sure that `Person.Address` is also populated. ✔
   - Adding null validation to all the `Person` and `Address` properties is **optional**.
   - Consider using `ISampleData.CsvRows` in your test to verify your results. ❌

5. Implement `ISampleDate.FilterByEmailAddress(Predicate<string> filter)` to return a list of names where the email address matches the `filter`. ✔

   - Use `ISampleData.People` for your data source. ✔

6. Implement `ISampleData.GetAggregateListOfStatesGivenPeopleCollection(IEnumerable<IPerson> people)` to return a `string` that contains a **unique**, comma-separated list of states. ✔

   - Use the `people` parameter from `ISampleData.People` property for your data source. ✔
   - At a minimum, use the `System.Linq.Enumerable.`Aggregate` LINQ method to create your result. ✔
   - Don't forget the list should be unique. ✔
   - It is recommended that, at a minimum, you use `ISampleData.GetUniqueSortedListOfStatesGivenCsvRows` to validate your result.
     - **This is technically done since GetAggregateSortedListOfStatesUsingCsvRows() uses the aforementioned method to calculate its data, but it might be good to specifically use the IEnumerable return method.**

7. Given the implementation of `Node` in Assignment5

- Implement `IEnumerable<T>` to return all the items in the "circle" of items. ✔
  - **I'm not quite knowledgeable enough to know if the ICollection solution satisfies this, so I'll give you the benefit of the doubt since it looks like everything else is there the way it should.**
- Add an `IEnumberable<T> ChildItems(int maximum)` method to `Node` that returns the remaining items with a maximum number of items returned less than `maximum`.  

## Extra Credit

- Implement the homework using async/await and multi-threading by defining a new `SampleDataAsync` class that implements `IAsyncSampleData`). Refactor your `SampleData` and `SampleDataAsync` classes with minimal duplication. Be sure to refactor your tests to re-use a significant amount of the test code for both implementations. ✔
  - **A lot of the tests don't properly utilize the Async methods correctly, I would suggest taking a look at the Messages section of the Error List in VS.**

## Fundamentals

- Place all shared project properties into a `Directory.Build.Props` file.
- Place all shared project items into a `Directory.Build.targets` file.
- Ensure nullable reference types is enabled  ✔
- Ensure that you turn on code analysis for all projects(EnableNETAnalyzers)  ✔
- Set `LangVersion` and the `TargetFramework` to the latest released versions available (preview versions optional)   ✔
- and enabled .NET analyzers for both projects ✔
- For this assignment, consider using `Assert.AreEqual<T>()` (the generic version)  ✔
- All of the above should be unit tested ✔
- Choose simplicity over complexity ✔

**Overall excellent understanding of _what_ needs to be done, but several methods don't use LINQ  like they should, along with several other minor issues like test methods, naming conventions, Async conventions, etc.**

2023-03-09 07:14 UTC, Afterlyte commented on Assignment/Assignment/Node.cs
> +                for (int i = 0; i < maximum && i < Count; i++) {
There's a better way of doing this than needing a Count property by utilizing the original node calling the method.

2023-03-09 07:15 UTC, Afterlyte commented
> > 
> 
> Hi Ian, We added a new commit that fixes some failing tests, to get a more updated version, please pull again. Thank you.

Unfortunately I didn't see this until I had finished my review, feel free to ignore my comments about whatever you fixed!

2023-03-09 21:47 UTC, jdriscoll1 commented on Assignment/Assignment.Tests/SampleDataTests.cs
> +            Assert.IsTrue(uniqueSortedListOfStates.Zip(uniqueSortedListOfStates.Skip(1), (curr, next) => string.Compare(curr, next) < 0).All(x => x));
Thanks

2023-03-09 21:47 UTC, jdriscoll1 commented on Assignment/Assignment/SampleData.cs
> +                return File.ReadAllLines("../../../../Assignment/People.csv").ToList().Skip(1);
Updated, thank you

2023-03-09 21:48 UTC, jdriscoll1 commented on Assignment/Assignment/SampleData.cs
> +                    result += result.Contains(curr.Address.State) ? "" : curr.Address.State + ",");
Great, thank you

2023-03-10 00:32 UTC, jdriscoll1 commented on Assignment/Assignment/SampleData.cs
> +        public string GetAggregateSortedListOfStatesUsingCsvRows() {
Fixed, thank you

2023-03-14 23:35 UTC, mmwoodfo commented on Assignment/Assignment.Interfaces/Assignment.Interfaces.csproj
> +    <PackageReference Include="System.Linq.Async" Version="6.0.1" />
Just FYI, if you add your package here the person running and building the app should not need to install it, it should just work. This seems to work fine without running that command.

2023-03-14 23:35 UTC, mmwoodfo commented on Assignment/Assignment.Tests/SampleDataAsyncTests.cs
> +            Person actual = (Person)people.FirstAsync().Result;
You should use await here rather than .Result

2023-03-14 23:35 UTC, mmwoodfo commented on Assignment/Assignment/SampleData.cs
> +                return File.ReadAllLines("../../../../Assignment/People.csv").ToList().Skip(1);
```suggestion
                return File.ReadAllLines("People.csv").ToList().Skip(1); 
```
You should be able to just do this

2023-03-14 23:35 UTC, mmwoodfo commented on Assignment/Assignment/SampleData.cs
> +            foreach (string row in CsvRows) {
Instead of foreach, you should be using select here

2023-03-14 23:35 UTC, mmwoodfo commented on Assignment/Assignment/SampleData.cs
> +                foreach (string row in CsvRows)
Again, this should be using select

2023-03-14 23:37 UTC, closed without merging