Assignment1
IntelliTect-Samples/EWU-CSCD371-2023-Winter pull request #18
Opened 2023-01-16 12:25 UTC by shweshipu

Issues 1 and 2 were solved

2023-01-17 06:26 UTC, mmoran314 requested changes
Pull Request title includes "Assignment 1" in the title ✔
Pull Request targets Assignment 1 branch ✔
Issue 1: Application no longer crashes ✔
Issue 2: Unit test properly passes  ✔

2023-01-17 06:26 UTC, mmoran314 commented on PrincessBrideTrivia/PrincessBrideTrivia/Program.cs
> +            return ((double)numberCorrectAnswers / (double)numberOfQuestions * 100) + "%";
Pull Request title includes "Assignment 1" in the title ✔
Pull Request targets Assignment 1 branch ✔
Issue 1: Application no longer crashes ✔
Issue 2: Unit test properly passes ✔
I'm not sure if it is something worth changing, but changing the arguments in the GetPercentCorrect method to doubles will take away the need to use casting on the variables in the percent correct calculation.
Other than that, it looks great and I do not see anything that would need to be changed.

2023-01-19 02:46 UTC, Joshua-Pedersen reviewed
Pull Request title includes "Assignment 1" in the title ✔
Pull Request targets Assignment 1 branch ✔
Issue 1: Application no longer crashes ✔
Issue 2: Unit test properly passes ✔

Changes clear and working.

2023-01-19 02:46 UTC, Joshua-Pedersen commented on PrincessBrideTrivia/PrincessBrideTrivia/Program.cs
> +            return ((double)numberCorrectAnswers / (double)numberOfQuestions * 100) + "%";
You could simplify this by just casting once. A ```double``` divided by an ```int``` will result in a ```double```
~~~
return ((double)numberCorrectAnswers / numberOfQuestions * 100) + "%";
~~~

2023-01-19 02:46 UTC, Joshua-Pedersen commented on PrincessBrideTrivia/PrincessBrideTrivia/Program.cs
> +                questions[i] = question;
Not sure if they are requiring this, but the added code isn't covered by a test. Could create a test to confirm the ```question``` is being placed into the ```questions``` array

2023-01-22 23:42 UTC, closed without merging