Fixing conflict
IntelliTect-Samples/EWU-CSCD371-2023-Winter pull request #26
Opened 2023-01-17 00:09 UTC by jstanley6

2023-01-17 06:39 UTC, mmoran314 requested changes
Pull Request title includes "Assignment 1" in the title ✔
Pull Request targets Assignment 1 branch ✔
Issue 1: Application no longer crashes ✔
Issue 2: Unit test properly passes ✔

2023-01-17 06:39 UTC, mmoran314 commented on PrincessBrideTrivia/PrincessBrideTrivia/Program.cs
> +            double numCorrectAns = numberCorrectAnswers;
Pull Request title includes "Assignment 1" in the title ✔
Pull Request targets Assignment 1 branch ✔
Issue 1: Application no longer crashes ✔
Issue 2: Unit test properly passes ✔
Looks good!
Only potential change I can think of is to either cast the arguments as doubles during the calculation or to change the arguments within the header of the GetPercentCorrect method from ints to doubles in order to not use as many lines of code.

2023-01-18 05:00 UTC, jstanley6 commented on PrincessBrideTrivia/PrincessBrideTrivia/Program.cs
> +            double numCorrectAns = numberCorrectAnswers;
Completed your suggestions.

2023-01-19 05:09 UTC, Wvvern commented
Will review

2023-01-19 05:55 UTC, Wvvern reviewed
Pull Request title includes "Assignment 1" in the title ✔
Pull Request targets Assignment 1 branch ✔
Issue 1: Application no longer crashes ✔
Issue 2: Unit test properly passes ✔

2023-01-19 05:55 UTC, Wvvern commented on PrincessBrideTrivia/PrincessBrideTrivia/Program.cs
> +            return ((numberCorrectAnswers / numberOfQuestions) * 100.0) + "%";
Since both numberCorrectAnswers and numberOfQuestions are stored as ints, the method parameters here should reflect that being the case. It's also not necessary to change them to doubles.

```suggestion
           double percentage = 100.0 * numberCorrectAnswers / numberOfQuestions;
           return Math.Round(percentage, 2) + "%";
```

Instead, something like this will prevent integer division from occuring. 
You could just explicitly cast to a double here, but even that is not necessary. 
Multiplication and division are of equal weight within the order of operations, so the multiplication will occur first. 
Once the multiplication occurs, the numerator becomes a double and forces the denominator to be promoted to a double. Thus, resolving the integer division problem.

2023-01-19 05:55 UTC, Wvvern commented on PrincessBrideTrivia/PrincessBrideTrivia/Program.cs
> +            if(filePath == null)
This check is not necessary. In c#, a null value should never be passed to a non-nullable parameter, and is treated as a warning. The parameter "filePath" has no question mark at the end, indicating (by default) that it's non-nullable.
Instead, you could check if it's a valid file path.

2023-01-22 23:29 UTC, closed without merging