Assignment 2 @crawfordkid2 & @GeorgeKoralski007
IntelliTect-Samples/EWU-CSCD371-2023-Winter pull request #46
Opened 2023-01-24 02:32 UTC by crawfordkid2

2023-01-26 00:29 UTC, Afterlyte commented
I will review this

2023-01-26 00:58 UTC, Afterlyte requested changes
- There is an existing `BaseLogger` class. It needs an **auto property** to hold a class name. This property should be set in the `LogFactory` using an **object initializer**. ❌
  - ClassName needs to be set using an object initializer in LogFactory, and should be set to the name of the class _calling_ the CreateLogger method, not the FileLogger object itself
- Create a `FileLogger` that derives from `BaseLogger`. It should take in a path to a file to write the log message to. When its `Log` method is called, it should **append** messages on their own line in the file. The output should include all of the following:
  - The current date/time ✔
  - The name of the class that created the logger ❌
    - See bullet 1
  - The log level ✔
  - The message ✔
  - The format may vary, but an example might look like this "10/7/2019 12:38:59 AM FileLoggerTests Warning: Test message"
- The `LogFactory` should be updated with a new method `ConfigureFileLogger`. This should take in a file path and store it in a **private member**. It should use this when instantiating a new `FileLogger` in its `CreateLogger` method. ❌
  - ConfigureFileLogger either missing or misplaced
- If the file logger has not be configured in the `LogFactory`, its `CreateLogger` method should return `null`. ✔
 - Done correctly even though ConfigureFileLogger is missing
- Inside of `BaseLoggerMixins` implement **extension methods** on `BaseLogger` for
  - `Error`, ✔
  - `Warning`, ✔
  - `Information`, and ✔
  - `Debug`. ✔ 
  - Each of these methods should take in a `string` for the message, as well as a **parameter array** of arguments for the message. Each of these extension methods is expected to be a shortcut for calling the `BaseLogger.Log` method, by automatically supplying the appropriate `LogLevel`. These methods should throw an exception if the `BaseLogger` parameter is null. There are a couple example unit tests to get you started.
- Use the nameof() operator when identifying the class name to the logger ❌
  - Goes with modifying how the ClassName is set and handled
- Ensure you turn on Warnings as Errors (TreatWarningsAsErrors) ✔
- Ensure that you turn on code analysis (EnableNETAnalyzers) ✔
- Ensure that you turn on CodeAnalysisTreatWarningsAsErrors ✔
- Set `LangVersion` and the `TargetFramework` to the latest released versions available (preview versions optional) ✔
- Turn on Nullability (`Nullable`) ✔
- **All of the above should be unit tested.**
  - Unit tests need to be added for missed pieces like ConfigureFileLogger

2023-01-26 00:58 UTC, Afterlyte commented on Logger/LogFactory.cs
> +                    return new FileLogger(filePath);
Object initializer needs to be used here to set ClassName, otherwise you're never doing anything with the className parameter that's passed in.

2023-01-26 00:58 UTC, Afterlyte commented on Logger.Tests/BaseLoggerMixinsTests.cs
> +        }
I would recommend using the Arrange Act Assert structure for tests with more lines of code like this to make them easier to read.
```suggestion
        [TestMethod]
        public void TestError_WithMessageArgs()
        {
            // Arrange
            string path = Path.GetTempFileName();
            if (File.Exists(path))
                File.Delete(path);
            FileLogger logger = new FileLogger(path);
            logger.Error("Error_Message_{0}_{1}_{2}", 1, 2, 3);
            DateTime expectedDate = DateTime.Now;
            
            // Act
            StreamReader sr = File.OpenText(path);
            string actualContents = sr.ReadLine();
            
            // Assert
            Assert.AreEqual($"{expectedDate} FileLogger Error: Error_Message_1_2_3", actualContents);
            sr.Close();
            File.Delete(path);
        }
```

2023-01-26 00:58 UTC, Afterlyte commented on Logger/LogFactory.cs
> +                //    throw new InvalidOperationException("You need to call ConfigureFileLogger first to set the path");
ConfigureFileLogger needs to be implemented and placed in this class, and needs to be the method handling the FilePath member.

2023-01-26 00:58 UTC, Afterlyte commented on Logger/LogFactory.cs
> +        private string filePath = null;
If this is supposed to be a property it needs to be changed to match name and structure conventions (basically like how you have Name set up)

2023-01-26 00:58 UTC, Afterlyte commented on Logger/LogFactory.cs
>              return null;
This should probably be changed to check for null first, then else returning the correct object so it doesn't look like null is the end result. i.e. if FilePath is null, return null, else return a new FileLogger

2023-01-26 02:57 UTC, JessicaH46 commented
There is an existing BaseLogger class. It needs an auto property to hold a class name. This property should be set in the LogFactory using an object initializer. ❌
Create a FileLogger that derives from BaseLogger. It should take in a path to a file to write the log message to. When its Log method is called, it should append messages on their own line in the file. The output should include all of the following:
The current date/time ✔
The name of the class that created the logger ✔
The log level ✔
The message ✔
The format may vary, but an example might look like this "10/7/2019 12:38:59 AM FileLoggerTests Warning: Test message"
The LogFactory should be updated with a new method ConfigureFileLogger. This should take in a file path and store it in a private member. It should use this when instantiating a new FileLogger in its CreateLogger method. ❌✔
If the file logger has not be configured in the LogFactory, its CreateLogger method should return null. ✔
Inside of BaseLoggerMixins implement extension methods on BaseLogger for
Error, ✔
Warning, ✔
Information, and ✔
Debug. ✔ Each of these methods should take in a string for the message, as well as a parameter array of arguments for the message. Each of these extension methods is expected to be a shortcut for calling the BaseLogger.Log method, by automatically supplying the appropriate LogLevel. These methods should throw an exception if the BaseLogger parameter is null. There are a couple example unit tests to get you started.
Use the nameof() operator when identifying the class name to the logger ✔
Ensure you turn on Warnings as Errors (TreatWarningsAsErrors) ✔
Ensure that you turn on code analysis (EnableNETAnalyzers) ✔
Ensure that you turn on CodeAnalysisTreatWarningsAsErrors ✔
Set LangVersion and the TargetFramework to the latest released versions available (preview versions optional) ✔
Turn on Nullability (Nullable) ✔
All of the above should be unit tested.

I think most your code looks good and you completed most of the tasks from the code I saw. The biggest missing part is the ConfigureFileLogger method as I couldn't find that in your files. I think many of the smaller errors have been commented on and I don't have much to add on to those points. Good job on your work!

2023-01-31 04:53 UTC, mmwoodfo commented on Logger.Tests/FileLoggerTests.cs
> +    public class FileLoggerTests
It looks like you've declared this class twice? This is causing your code not to compile.

2023-01-31 04:53 UTC, mmwoodfo commented on Logger.Tests/LogFactoryTests.cs
> +public class LogFactoryTests
Same issue here, you've declared the class twice

2023-01-31 04:53 UTC, mmwoodfo commented on Logger.Tests/LogFactoryTests.cs
> +        }
What is the difference between these two tests? And what are you trying to test here? The test name is not specific

2023-01-31 04:53 UTC, mmwoodfo commented on Logger/LogFactory.cs
> +        public BaseLogger? CreateLogger(string className) {
This className parameter should be getting used to set the BaseLogger's class name for the FileLogger and your extra credit Console Logger

2023-01-31 04:53 UTC, mmwoodfo commented on Logger/FileLogger.cs
> +            ClassName = nameof(FileLogger);
This class name should be the name of the class creating the FileLogger, not the name of the FileLogger class. It should be getting set in the CreateLogger method in the LogFactory.

2023-01-31 04:53 UTC, mmwoodfo commented on Logger/FileLogger.cs
> +        private string FilePath { get; set; }
```suggestion
        private string _FilePath { get; set; }
```

2023-01-31 04:53 UTC, mmwoodfo commented on Logger/FileLogger.cs
> +            streamWriter.Close();
Good job closing your StreamWriter, but if you use the [`using`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement) keyword when setting up your StreamWriter on line 22, you don't need to worry about disposing of your stream writer here.

2023-01-31 04:53 UTC, mmwoodfo commented on Logger/FileLogger.cs
> +            string outLog = $"{date} {ClassName} {Enum.GetName(typeof(LogLevel), level)}: {message}";
```suggestion
            string outLog = $"{date} {ClassName} {level}: {message}";
```
Using your LogLevel in string interpolation like this will retrieve the name of the enum value for you.

2023-01-31 04:53 UTC, mmwoodfo commented on Logger/LogFactory.cs
> +            this.filePath = filePath;
```suggestion
            _FilePath = filePath;

```

2023-01-31 04:53 UTC, mmwoodfo commented on Logger/LogFactory.cs
> +        private string? filePath;
```suggestion
        private string? _FilePath;

```

2023-01-31 04:53 UTC, mmwoodfo commented on Logger/LogFactory.cs
> +            {
Instead of using an if/else latter here, you could consider using a switch with an enum or using generics

2023-01-31 04:53 UTC, mmwoodfo commented on Logger/BaseLoggerMixins.cs
> +            if (log == null)
```suggestion
            if (log is null)
```
Could use `is` keyword to match on null

Also, you could pull this out into a private static helper method that takes a BaseLogger and throws if it's null, so you don't have to write it out an additional 3 times

2023-01-31 04:53 UTC, mmwoodfo commented on Logger/BaseLoggerMixins.cs
> +        public static void Error(this BaseLogger log, string message, params object[] args)
```suggestion
        public static void Error(this BaseLogger logger, string message, params object[] args)
```
This should probably be called `logger`, not `log` as it's not a log message

2023-01-31 04:55 UTC, mmwoodfo commented on Logger/LogFactory.cs
> +                //    throw new InvalidOperationException("You need to call ConfigureFileLogger first to set the path");
@Afterlyte Great feedback, good job on your peer review!

2023-01-31 04:55 UTC, closed without merging

2023-02-05 01:10 UTC, GeorgeKoralski007 commented on Logger.Tests/FileLoggerTests.cs
> +    public class FileLoggerTests
Looks like merging problem. It was intended to have only one.

2023-02-05 01:17 UTC, GeorgeKoralski007 commented on Logger.Tests/LogFactoryTests.cs
> +        }
FileLogger actually exists but result is null because file path is not previously set.

2023-02-05 01:18 UTC, GeorgeKoralski007 commented on Logger/BaseLoggerMixins.cs
> +        public static void Error(this BaseLogger log, string message, params object[] args)
Agree

2023-02-05 01:22 UTC, GeorgeKoralski007 commented on Logger/FileLogger.cs
> +            ClassName = nameof(FileLogger);
Yes. I do set it in LogFactory.CreateLogger
But also decided to set it here in case someone create the logger using the constructor. Otherwise it is better to make constructor "internal"