Assignment 2
IntelliTect-Samples/EWU-CSCD371-2023-Winter pull request #47
Opened 2023-01-24 02:54 UTC by TriciaFaust

2023-01-26 01:12 UTC, Bhopss152 commented on Logger.Tests/LogFactoryTests.cs
> +            Assert.AreEqual("C:\\Logs\\LogFactoryTests.log", fileLogger.PathName);
Hard coding a path is not the best since if another user want to use it on their pc it wouldnt work right.

2023-01-26 01:12 UTC, Bhopss152 commented on Logger.Tests/FileLoggerTests.cs
> +            logFactory.ConfigureFileLogger("C:\\Logs");
Same thing here with the path.

2023-01-26 05:56 UTC, GeorgeKoralski007 commented on Logger.Tests/LogFactoryTests.cs
> +            Assert.AreEqual("C:\\Logs\\LogFactoryTests.log", fileLogger.PathName);
To add to what Bhopss152 said, I would make a Tempfile and then have the file in the Tempfile deleted so it does not overwrite itself.

2023-01-26 07:27 UTC, GeorgeKoralski007 commented on Logger/BaseLogger.cs
> +        public string PathName { get; set; }
PathName should be defined in FileLogger class. Base class does not need it because its not common for all loggers.

2023-01-26 07:45 UTC, GeorgeKoralski007 requested changes

2023-01-26 07:45 UTC, GeorgeKoralski007 commented on Logger/LogFactory.cs
> +            FileLogger fileLogger = new FileLogger(outputPath);
FileLogger should only be created when className parameter is "FileLogger"
Otherwise it should return null

2023-01-26 07:45 UTC, GeorgeKoralski007 commented on Logger/LogFactory.cs
> +        private string ClassName;
This is not needed

2023-01-26 07:45 UTC, GeorgeKoralski007 commented on Logger/LogFactory.cs
> +            fileLogger.Name = ClassName;
Remove the ClassName and use only the parameter className here

2023-01-26 07:45 UTC, GeorgeKoralski007 commented on Logger/LogFactory.cs
> +            string outputPath = Path.Combine(OutputPath, ClassName + ".log");
Check if OutputPath is previously set. If still null then return null because we cannot create FileLogger.
OutputPath should have the filename in it also (not only folder)

2023-01-26 07:45 UTC, GeorgeKoralski007 commented on Logger.Tests/LogFactoryTests.cs
> +            var fileLogger = logFactory.CreateLogger(nameof(LogFactoryTests));
It should use nameof(FileLogger)

2023-01-26 07:45 UTC, GeorgeKoralski007 commented on Logger/LogFactory.cs
> +            OutputPath = pathName;
This should be the full file path including the file name.
Currently you are using it as a directory path only.

2023-02-01 02:37 UTC, mmwoodfo reviewed
![image](https://user-images.githubusercontent.com/43832670/215931545-4516e680-44a6-4051-817a-a0ede2edecb5.png)


Make sure your PR is going against the correct branch, in this case, it should be going against the Assignment 2 branch.

2023-02-01 02:37 UTC, closed without merging