Assignment2
IntelliTect-Samples/EWU-CSCD371-2023-Winter pull request #57
Opened 2023-01-24 06:47 UTC by FenrisStargazer

abrand3 / FenrisStargazer, no partner

2023-01-25 03:46 UTC, alowe4 commented on Logger.Tests/BaseLoggerMixinsTests.cs
>          // Assert
Error_WithNullLogger_ThrowsException does not assert anything, 
I saw that BaseLoggerMixins can throw an ArgumentNullException
try to use Assert.ThrowsException<> to test

2023-01-25 03:46 UTC, alowe4 commented on Logger/FileLogger.cs
> +        this.filePath = filePath;
same as in log factory, avoid the "this" keyword, and use pascal case.

2023-01-25 03:46 UTC, alowe4 commented on Logger/LogFactory.cs
> +            this.filePath = filePath;
1. you want to avoid the 'this' keyword. Instead make the filePath on line 5 FilePath and use that. 
2. capitalize configure in configureFileLogger

2023-01-25 03:49 UTC, alowe4 requested changes
There is an existing BaseLogger class. It needs an auto property to hold a class name. This property should be set in the LogFactory using an object initializer. ✔
Create a FileLogger that derives from BaseLogger. It should take in a path to a file to write the log message to. When its Log method is called, it should append messages on their own line in the file. The output should include all of the following:

    The current date/time ✔
    The name of the class that created the logger ✔
    The log level ✔
    The message ✔
    The format may vary, but an example might look like this "10/7/2019 12:38:59 AM FileLoggerTests Warning: Test message"

The LogFactory should be updated with a new method ConfigureFileLogger. This should take in a file path and store it in a private member. It should use this when instantiating a new FileLogger in its CreateLogger method. ✔
If the file logger has not be configured in the LogFactory, its CreateLogger method should return null. ✔
Inside of BaseLoggerMixins implement extension methods on BaseLogger for

    Error, ✔
    Warning, ✔
    Information, and ✔
    Debug. ✔ 
Each of these methods should take in a string for the message, as well as a parameter array of arguments for the message. Each of these extension methods is expected to be a shortcut for calling the BaseLogger.Log method, by automatically supplying the appropriate LogLevel. 
These methods should throw an exception if the BaseLogger parameter is null. ✔[not properly tested, but exists]
There are a couple example unit tests to get you started.

Use the nameof() operator when identifying the class name to the logger ✔
Ensure you turn on Warnings as Errors (TreatWarningsAsErrors) ✔
Ensure that you turn on code analysis (EnableNETAnalyzers) ✔
Ensure that you turn on CodeAnalysisTreatWarningsAsErrors ✔
Set LangVersion and the TargetFramework to the latest released versions available (preview versions optional) ✔
Turn on Nullability (Nullable) ✔

2023-01-26 03:29 UTC, FenrisStargazer commented on Logger.Tests/BaseLoggerMixinsTests.cs
>          // Assert
The assertion for that test is done through the "[ExpectedException(typeof(ArgumentNullException))]" on line 11.

2023-01-26 06:23 UTC, eroadhouse reviewed
There is an existing BaseLogger class. It needs an auto property to hold a class name. This property should be set in the LogFactory using an object initializer. ✔
Create a FileLogger that derives from BaseLogger. It should take in a path to a file to write the log message to. When its Log method is called, it should append messages on their own line in the file. The output should include all of the following:
The current date/time ✔
The name of the class that created the logger ✔
The log level ✔
The message ✔
The format may vary, but an example might look like this "10/7/2019 12:38:59 AM FileLoggerTests Warning: Test message"
The LogFactory should be updated with a new method ConfigureFileLogger. This should take in a file path and store it in a private member. It should use this when instantiating a new FileLogger in its CreateLogger method. ✔
If the file logger has not be configured in the LogFactory, its CreateLogger method should return null. ✔
Inside of BaseLoggerMixins implement extension methods on BaseLogger for
Error, ✔
Warning, ✔
Information, and ✔
Debug. ✔ Each of these methods should take in a string for the message, as well as a parameter array of arguments for the message. Each of these extension methods is expected to be a shortcut for calling the BaseLogger.Log method, by automatically supplying the appropriate LogLevel. These methods should throw an exception if the BaseLogger parameter is null. There are a couple example unit tests to get you started.
Use the nameof() operator when identifying the class name to the logger ✔
Ensure you turn on Warnings as Errors (TreatWarningsAsErrors) ✔
Ensure that you turn on code analysis (EnableNETAnalyzers) ✔
Ensure that you turn on CodeAnalysisTreatWarningsAsErrors ✔
Set LangVersion and the TargetFramework to the latest released versions available (preview versions optional) ✔
Turn on Nullability (Nullable) ✔
All of the above should be unit tested.

Overall, nicely done!

2023-01-26 06:23 UTC, eroadhouse commented on Logger.Tests/BaseLoggerMixinsTests.cs
> +    public override string ClassName { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
Here you should probably throw something else other than a NotImplementedException() since this code is technically implemented

2023-01-26 06:23 UTC, eroadhouse commented on Logger.Tests/FileLoggerTests.cs
> +namespace Logger.Tests
Converting to file-scoped namespaces will be good here and for the future

2023-01-26 06:23 UTC, eroadhouse commented on Logger.Tests/BaseLoggerMixinsTests.cs
> +    public void Warning_LogsMessage()
I think it'd be a good idea to also test a null logger in Warning, Information, and Debug as well and not just Error

2023-02-02 23:16 UTC, mmwoodfo commented on Logger/LogFactory.cs
> +                FileLogger fileLogger = new FileLogger(FilePath) {ClassName = className};
```suggestion
                FileLogger fileLogger = new(FilePath) {ClassName = className};
```

2023-02-02 23:16 UTC, mmwoodfo commented on Logger/FileLogger.cs
> +        file.WriteLineAsync(DateTime.Now + " " + ClassName + " " + logLevel + ": " + message);
I'd recommend using string interpolation here `$"{DateTime.Now} {ClassName} etc..."`

2023-02-02 23:16 UTC, mmwoodfo commented on Logger/FileLogger.cs
> +        StreamWriter file = new StreamWriter(FilePath, true);
Make sure you close your stream writer or warp it in a using statement.

2023-02-02 23:16 UTC, mmwoodfo commented on Logger/LogFactory.cs
> +        private string? FilePath { get; set; }
```suggestion
        private string? _FilePath;
```
This doesn't need to be an auto property, it can just be a private field.

2023-02-02 23:16 UTC, mmwoodfo commented on Logger/BaseLoggerMixins.cs
> +    public static void Error(this BaseLogger b, string message, params object[] arguments)
```suggestion
    public static void Error(this BaseLogger logger, string message, params object[] arguments)
```
Avoid using single-character variable names, I'd recommend calling this something like `logger` instead.

2023-02-02 23:16 UTC, mmwoodfo commented on Logger/BaseLoggerMixins.cs
> +            throw new ArgumentNullException();
```suggestion
            throw new ArgumentNullException(nameof(logger));
```
Make sure to specify what argument is throwing the null exception

2023-02-02 23:16 UTC, mmwoodfo commented on Logger/FileLogger.cs
> +        ClassName = "";
```suggestion
```

2023-02-02 23:16 UTC, mmwoodfo commented on Logger/BaseLogger.cs
> +        public abstract string ClassName { get; set; }
```suggestion
        public string? ClassName { get; set; }
```
This doesn't need to be abstract here, but it's not wrong depending on how you intend this to be used. Also, it's okay to mark this as nullable, you just need to make sure that you're expecting that it can be null.

2023-02-03 00:36 UTC, closed without merging