Assignment3 Alan and Grant
IntelliTect-Samples/EWU-CSCD371-2023-Winter pull request #70
Opened 2023-01-31 02:03 UTC by Howard404

Assignment 3: Alan Rose (@arose-13) and Grant Howard (@Howard404)

2023-02-02 02:37 UTC, GeorgeKoralski007 commented
For this assignment do the following:

Create two interfaces. One to represent the JokeService and one interface to represent outputting the joke to the screen (Console.WriteLine). ✔
The JokeService will need to have the interface applied to it. ✔
Create an implementation of the output interface that writes out the joke to the console. ✔
Implement the Jester class. It should take in both interfaces as dependencies. These dependencies should be null checked. ❌
The Jester class TellJoke() method should retrieve a joke from the JokeService. If the joke contains "Chuck Norris", skip it and get another. The joke should be written to the output dependency. ❌
Unit test the Jester class. Code coverage should be above 90% for this class. Moq will make this significantly easier. ✔
Fundamentals
Be sure you enable:
Nullability for all projects ✔
Set LangVersion and the TargetFramework to the latest released versions available (preview versions optional) ✔
Ensure that you turn on code analysis for all projects(EnableNETAnalyzers) ✔
For this assignment, always use Assert.AreEqual<T>() (the generic version) ✔
Ensure there are no errors or warnings (including code analysis warnings) ✔
All of the above should be unit tested ✔
Choose simplicity over complexity ✔
Extra Credit
Unit test your implementation that writes the joke out to the screen. How hard could it be to unit test a single line method ;)? ✔
The Geek jokes API that is being used can also return jokes in a JSON format. Update the JokeService to retrieve jokes using JSON. GetJoke should still return a string. ❌

2023-02-02 02:39 UTC, GeorgeKoralski007 commented on CanHazFunny/CanHazFunny/JokeService.cs
> +public class JokeService : IJokeRetrieve, IJokeDisplay
IJokeDisplay should be implemented in a different JokeDisplay class as required.

2023-02-02 02:43 UTC, GeorgeKoralski007 commented on CanHazFunny/CanHazFunny/Jester.cs
> +    public Jester(JokeService service)
Requirements said to take two interfaces here in the constructor, not a specific service type.
Check both of them for null in the constructor.

2023-02-02 02:45 UTC, GeorgeKoralski007 commented on CanHazFunny/CanHazFunny/Jester.cs
> +        string joke = Service.GetJoke();
You are getting a joke only once and filter it. It is required to re-try getting a new joke if it does not pass the filter.

2023-02-02 02:45 UTC, GeorgeKoralski007 commented on CanHazFunny/CanHazFunny/Jester.cs
> +            Service.Display("That wasn't a very good joke, let me think of another one.");
Not needed if you retry with while loop to get correct joke

2023-02-02 02:46 UTC, GeorgeKoralski007 commented on CanHazFunny/CanHazFunny/Jester.cs
> +        if (!string.IsNullOrWhiteSpace(joke) &&
Could be optimized to just return the if statement

2023-02-02 02:49 UTC, GeorgeKoralski007 commented on CanHazFunny/CanHazFunny.Tests/JesterTests.cs
> +            Assert.IsNotNull(joke);
You only test not non null/empty joke.
You should Assert the content is the expected one if you use mock service.

2023-02-02 02:50 UTC, GeorgeKoralski007 commented on CanHazFunny/CanHazFunny.Tests/JesterTests.cs
> +            Assert.IsFalse(result);
You should also have a test for true case.

2023-02-02 02:53 UTC, GeorgeKoralski007 requested changes
Please review the comments and fix as needed.

2023-02-07 22:56 UTC, mmwoodfo commented on CanHazFunny/CanHazFunny/Jester.cs
> +            Service.Display("That wasn't a very good joke, let me think of another one.");
I don't think you have a display method on your JokeService dependency. Your code isn't compiling because of this.

2023-02-07 22:56 UTC, mmwoodfo commented on CanHazFunny/CanHazFunny/IJokeDisplay.cs
> +public interface IJokeDisplay
It doesn't seem like this is being implemented anywhere

2023-02-07 22:56 UTC, mmwoodfo commented on CanHazFunny/CanHazFunny.Tests/CanHazFunny.Tests.csproj
> +    <TargetFramework>net7.0</TargetFramework>
```suggestion
    <TargetFramework>net7.0</TargetFramework>
    <WarningsAsErrors>true</WarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>        
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors> 
    <LangVersion>11.0</LangVersion>
    <Nullable>enable</Nullable>
```

2023-02-07 22:56 UTC, mmwoodfo commented on CanHazFunny/CanHazFunny/Jester.cs
> +    public JokeService Service
```suggestion
    private IJokeService? _Service;
    public IJokeService Service 

```
This should be your interface

2023-02-07 22:56 UTC, closed without merging