Assignment3: Jacob Newcomb and Jessica Ho
IntelliTect-Samples/EWU-CSCD371-2023-Winter pull request #83
Opened 2023-01-31 07:46 UTC by jacobnewcomb

With @JessicaH46

2023-01-31 15:39 UTC, StrangeRanger commented
Will review

2023-01-31 18:05 UTC, StrangeRanger commented on CanHazFunny/CanHazFunny.Tests/JesterTests.cs
> +            string joke = jester.TellJoke();
You are trying to have TellJoke return a value when TellJoke is set to void, as to return nothing.

2023-01-31 18:14 UTC, StrangeRanger requested changes

2023-01-31 18:14 UTC, StrangeRanger commented on CanHazFunny/CanHazFunny.Tests/JesterTests.cs
> +            Assert.IsNotNull(joke);
```suggestion
            Assert.IsNotNull(jester.TellJoke());
```

2023-01-31 18:14 UTC, StrangeRanger commented on CanHazFunny/CanHazFunny.Tests/JesterTests.cs
> +            //Assert
```suggestion
```

2023-01-31 18:14 UTC, StrangeRanger commented on CanHazFunny/CanHazFunny.Tests/JesterTests.cs
> +            Assert.IsNotNull(joke);
```suggestion
```

2023-02-01 18:54 UTC, StrangeRanger reviewed
## Assignment

For this assignment do the following:

- Create *two* interfaces. One to represent the `JokeService` and one interface to represent outputting the joke to the screen (`Console.WriteLine`). ✔
- The `JokeService` will need to have the interface applied to it. ✔
- Create an implementation of the output interface that writes out the joke to the console. ✔
- Implement the `Jester` class. It should take in both interfaces as dependencies. These dependencies should be null checked. ❌
  - **REVIEW NOTE:** Does not take both interfaces and dependencies.
- The `Jester` class `TellJoke()` method should retrieve a joke from the `JokeService`. If the joke contains "Chuck Norris", skip it and get another. The joke should be written to the output dependency. ✔
- Unit test the Jester class. Code coverage should be above 90% for this class. Moq will make this significantly easier. ❌
  - **REVIEW NOTE:** Can't perform unit testing, and therefore can't check code coverage of the Jester class.

## Fundamentals

- Be sure you enable:
  - Nullability for all projects  ❌
    - **REVIEW NOTE:** Nullability isn't set for `CanHazFunny.Test`.
  - Set `LangVersion` and the `TargetFramework` to the latest released versions available (preview versions optional) ❌
    - **REVIEW NOTE:** `TargetFramework` is set to `net6.0`.
  - Ensure that you turn on code analysis for all projects(EnableNETAnalyzers) ❌
    - **REVIEW NOTE:** Not enabled for `CanHazFunny.Test`.
- For this assignment, always use `Assert.AreEqual<T>()` (the generic version)  ✔
- **Ensure there are no errors or warnings (including code analysis warnings)** ❌
- **All of the above should be unit tested** ❌
- **Choose simplicity over complexity** ✔

## Extra Credit

- Unit test your implementation that writes the joke out to the screen. How hard could it be to unit test a single line method ;)?
- The Geek jokes API that is being used can also return jokes in a JSON format. Update the `JokeService` to retrieve jokes using JSON. `GetJoke` should still return a string.

## OTHER NOTES

Please let me know if you have any questions on anything I've said. I hope my comments are coherent enough to understand. If you believe I made an incorrect suggestion, don't hesitate to tell or ask me why I suggested it.

2023-02-01 18:54 UTC, StrangeRanger commented on CanHazFunny/CanHazFunny.Tests/JesterTests.cs
> +            string joke = jester.TellJoke();
This line throws a compile time error because you are trying to store some returned value from `TellJoke()` when that method doesn't return anything. I'd suggest using the StringWriter object like I provided for the suggestion below.

2023-02-01 18:54 UTC, StrangeRanger commented on CanHazFunny/CanHazFunny/Jester.cs
> +        private JokeService? _jokeService;
```suggestion
        private IService? _JokeService;
```
You should be using the interface type `IService` instead of `JokeService`. Additionally, make sure private class fields are PascalCase. You'll need to modify all existing occurrences of `_jokeService` with `_JokeService`.

2023-02-01 18:54 UTC, StrangeRanger commented on CanHazFunny/CanHazFunny/Jester.cs
> +        private JokeServiceWriter? _jokeServiceWriter;
```suggestion
        private IServiceWriter? _JokeServiceWriter;
```
You should be using the interface type `IServiceWriter` instead of `JokeServiceWriter`. Additionally, make sure private class fields are PascalCase. You'll need to modify all existing occurrences of `_jokeServiceWriter` with `_JokeServiceWriter`.

2023-02-01 20:26 UTC, StrangeRanger commented on CanHazFunny/CanHazFunny.Tests/JesterTests.cs
> +        }
```suggestion
        public void JokeService_DoesntTellChuckNorrisJokes_Please() 
        {
            StringWriter stringWriter = new StringWriter();
            Console.SetOut(stringWriter);

            // Act
            Jester?.TellJoke();

            // Assert
            Assert.IsFalse(stringWriter.ToString().Contains("Chuck Norris"));
        }
```
There is an easier way of doing this. I'd recommend using something similar to the changes I provided. It essentially allows you to capture the unit test output and do with it as you want.

2023-02-02 21:12 UTC, JessicaH46 commented on CanHazFunny/CanHazFunny.Tests/JesterTests.cs
> +        public void JokeService_TellsJoke()
```suggestion
        public void JokeService_TellsJoke()
```
public void JokeService_TellsJoke_IsNotNull()

2023-02-02 22:18 UTC, JessicaH46 commented on CanHazFunny/CanHazFunny.Tests/JesterTests.cs
> +        public void JokeService_TellsJoke()
Thank you I changed it to include IsNotNull!

2023-02-02 22:21 UTC, JessicaH46 commented on CanHazFunny/CanHazFunny/CanHazFunny.csproj
> +	  <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
Just wondering did you end up using this or anything similar at all for this bullet point ?
Ensure there are no errors or warnings (including code analysis warnings) ❌✔
As it said including code analysis we thought we should include that.

2023-02-02 22:24 UTC, JessicaH46 commented on CanHazFunny/CanHazFunny/Jester.cs
> +        private JokeServiceWriter? _jokeServiceWriter;
Thank you for the reminders, we really appreciated your review! Having so many naming conventions in other class we didn't notice we missed the pascal here. Thank you for the help!

2023-02-02 22:25 UTC, JessicaH46 commented on CanHazFunny/CanHazFunny.Tests/JesterTests.cs
> +            string joke = jester.TellJoke();
We ended up changing the return value to a string so that we can cast it to a string variable, this resolved the issue but thank you for your suggestion so that we could fix it!

2023-02-03 05:10 UTC, StrangeRanger commented on CanHazFunny/CanHazFunny/CanHazFunny.csproj
> +	  <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
@JessicaH46 Yea, I understand. But the code that "CodeAnalysisTreatWarningsAsErrors" was throwing for, was put their by the instructor and I doubt they really wanted or expected us to change it. So I'm hoping that they will be considerate about that. If they dock you for that, feel free to refer back to me/this comment. Whatever you think is best is probably the best.

2023-02-09 03:40 UTC, JLee35 commented on CanHazFunny/CanHazFunny.Tests/JesterTests.cs
> +        }
Awesome review @StrangeRanger

2023-02-09 03:44 UTC, JLee35 commented on CanHazFunny/CanHazFunny.Tests/JesterTests.cs
> +        public void JokeService_TellsJoke()
It doesn't look like the suggested fix to this was implemented.

2023-02-09 03:46 UTC, JLee35 commented on CanHazFunny/CanHazFunny.Tests/JesterTests.cs
> +        }
A good suggestion was made here. Plus, your test doesn't ensure "Chuck Norris" doesn't ever get returned, it just ensures the ten times you try it doesn't. Using a mocker would have been much more appropriate here.

2023-02-09 03:48 UTC, JLee35 commented on CanHazFunny/CanHazFunny/JokeService.cs
> +    public class JokeService : IService
`Service` itself is a very ambiguous name, hence why we used the name `JokeService`. This would be similar to naming something `Controller`, when really we need the what the class is controlling. 
```suggestion
    public class JokeService : IJokeService
```

2023-02-09 03:51 UTC, JLee35 commented
Overall good job. Next time ensure you are addressing peer review suggestions in the code before you resolve a comment (it's easy to forget to make the actual change suggested) Also, shoot for more thorough unit testing (use a mocker to ensure your code does what is expected with a given input instead of trying a bunch of times and calling it good)

2023-02-09 03:51 UTC, closed without merging