Assignment4 alan and grant
IntelliTect-Samples/EWU-CSCD371-2023-Winter pull request #93
Opened 2023-02-07 04:53 UTC by arose-13

2023-02-09 01:53 UTC, Afterlyte commented
I will review this

2023-02-09 02:27 UTC, Afterlyte requested changes
## Tasks

- Define a full name record (first, last, middle) handling optional and null appropriately. ✔
  - Provide a comment on the full name record on why you selected to define a value or a reference type and ❌
    - Needs comment
  - Provide a comment on the full name record on why or why not the type is immutable. ❌
    - Needs comment
- Define an `IEntity` interface: ✔
  - Add an Id property of type `Guid` that is an init-only setter. ✔
  - Add a Name property that is `string`. ✔
- Define an abstract base class that implements `IEntity` - appropriately choosing to implement the interface explicitly or implicitly. ✔
  - Do not implement the `Name` property in this abstract class. ✔
  - Do force any derived classes to provide an implementation for `Name`. ✔
- Define book, student, and employee records - all with entity capabilities. ✔
  - Choose a thoughtful approach for the value of `Name` for each type of entity. In all cases, there should be no backing field for Name (not even one generated by an automatically implemented property) - consider a calculated property. ✔
  - Provide a comment on each interface **member** in each entity explaining why you implemented it implicitly or explicitly. ❌
    - Needs comments
  - You should consider the relationship between Student and Employee and refactor the common code shared between them. ✔
    - Good job on BasePerson for shared code
  - Given the properties on the full name record, you should consider which entities it makes sense to use it. ✔
    - I like the use of FullName in book to hold the Author
  - Test that the equality behavior on these entities behaves as expected. ❌
    - Equality needs to be tested (beyond just what's done in the Storage class
  - Provide a comment on each interface method explaining why you implemented it implicitly or explicitly. ❌
    - Needs comments
- Unit test the Storage class using various entities to ensure that there are no bugs. ✔
- Code review (using TODO: comments if there are any issues - which there may not be) all logger-related classes.) 
  - Pay special attention to the CreateLogger methods throughout.
    - (I can't really review this part haha)

## Fundamentals

- Be sure you enable:
  - Enable Nullability for all projects  ✔
  - Set `LangVersion` and the `TargetFramework` to the latest released versions available (preview versions optional) ✔
  - Ensure that you turn on code analysis for all projects(EnableNETAnalyzers) ✔
- **Ensure there are no errors or warnings (including code analysis warnings)** ✔
- **All of the above should be unit tested** ✔
- **Choose simplicity over complexity** ✔

## Extra Credit

- Refactor your project files to put common properties and/or items into a single file. ❌
- Convert `ILogger.CreateLogger` to a generic method. ❌
  - Returns the logger classes type that is to be created. ❌
  - Has a type parameter for the configuration type ❌

Good job overall! Other than some tweaks to code and the comments/unit test stuff you nailed the requirements pretty well.

2023-02-09 02:27 UTC, Afterlyte commented on Logger.Tests/PersonTests.cs
> +        Student student = new(id, "John", "Williams", null);
An alternative to this could be to have FullName passed in as a parameter instead of the pieces of the name, that way since FullName is structured to allow MiddleName to be optional you never have to type null if you don't want a MiddleName, you just simply never provide it. However this works just as well.

2023-02-09 02:27 UTC, Afterlyte commented on Logger.Tests/StorageTests.cs
> +public class StorageTests
Good job testing Storage, all lines are fully covered!

2023-02-09 02:27 UTC, Afterlyte commented on Logger/BasePerson.cs
> +                return FullName.FirstName + " " + FullName.MiddleName + " " + FullName.LastName;
string.Format is a good way to make these return lines more readable, that way you don't have this string arithmetic going on for spaces and piecing it together.
```suggestion
                return string.Format($"{FullName.FirstName} {FullName.MiddleName} {FullName.LastName}");

```
(This is for this line as an example)

2023-02-09 02:27 UTC, Afterlyte commented on Logger/Employee.cs
> +    public string? Profession { get; set; }
We probably don't want these to be publicly changeable, as those are pretty concrete pieces of information for the most part/would be dangerous to allow being messed with easily.
```suggestion
    public int EmployeeID { get; }
    public string? Profession { get; }

```

2023-02-15 23:28 UTC, mmwoodfo commented on Logger/IEntity.cs
> +    public Guid Id { get; init; }
```suggestion
    Guid Id { get; init; }
```

2023-02-15 23:28 UTC, mmwoodfo commented on Logger/IEntity.cs
> +    public string Name { get; }
```suggestion
    string Name { get; }
```

2023-02-15 23:28 UTC, mmwoodfo commented on Logger/BasePerson.cs
> +        get
You could put a to string or calculated property on FullName, then you can do this formatting there!

2023-02-15 23:28 UTC, mmwoodfo commented on Logger.Tests/PersonTests.cs
> +public class PersonTests
What about book and student tests? You should also have tests for equality checking

2023-02-15 23:28 UTC, closed without merging